### ISSUE TITLE
Idea: Remind people to share data from previous flats

### ISSUE THREAD

**Issue by Echolon** [correctiv/wghh-landingpage#31]
Hi,

just had the idea to remind the people (if they are afraid) to share their old data, maybe from a previous contract they had. That's much easier for most, than "risking" to drop data from their current flat.

Kind regards

**Comment by k-nut** [comment]
Thank you for your proposal, nice to see that you actually discovered this repository!

You are raising a good point. Currently we are focusing on up to date data but of course we are open for people to contribute their old data as well. As it is going to be a lot of manual work to validate the data we will focus on the up-to-date data for now and not highlight the alternative to the users though.

But thanks again for the thought and for raising it here! 🙌

**Comment by Echolon** [comment]
If there is not enough incoming data, that's maybe a way to help people to contribute. Additionally, if you ask for specific 'Postleitzahlen' in case you are seeing 'white spots' on the map.

Cheers

**Comment by k-nut** [comment]
We're actually running an [outdoor art campaign] to gain more contributors today but the idea to specifically target PLZs is also good advice and we are actively monitoring from where we get submissions :)

[outdoor art campaign]: https://www.facebook.com/events/825429100996010/
